# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "67a8f61ca9ad53a07e0f732ba385700b"
name = "lingotuner-translate-app"
application_url = "https://lingotuner-shopify.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_locales,read_translations,write_translations"

[auth]
redirect_urls = [
  "https://lingotuner-shopify.vercel.app/auth/callback",
  "https://lingotuner-shopify.vercel.app/auth/shopify/callback"
]
